### ISSUE TITLE
[Feature request] Widget for the android app 

### ISSUE THREAD

**Issue by mulles** [aykit/MyOwnNotes#120] opened 2015-07-25 21:00 UTC
As for the app https://github.com/atd/HandyNotes  

I would find it useful to have a widget to take notes which are right away uploaded to owncloud instance as it is now already the case, thx to the amazing work of you :) 

See here for an illustrating example: 
https://e1000.atria.uberspace.de/owncloud/index.php/s/PWHeTwYPKBVwCAZ

maybe it is straight forward and the code of HandyNotes can be reused?!

**Comment by jancborchardt** [comment] 2015-08-09 12:59
Hey @mulles, this is a duplicate of issue https://github.com/aykit/MyOwnNotes/issues/38 – let’s continue there. :)

**Comment by ramschmaerchen** [comment] 2015-08-09 15:55
Dear @jancborchardt , thanks for referring!

**Closed by ramschmaerchen** 2015-08-09 15:55 UTC
