### ISSUE TITLE
FR:it does not show up in the share app list

### ISSUE THREAD

**Issue by irregularisnotrandom** [aykit/MyOwnNotes#113] opened 2015-05-24 21:53 UTC
Hi

It would be great if this app shows up in the shared app dropdowns ao one could send content directly to the note app.

Thanks

**Comment by ramschmaerchen** [comment] 2015-06-12 16:54
Will be available in 2.0

**Comment by ramschmaerchen** [comment] 2017-03-27 20:26
Did not make it into 2.0, duplicate of #89

**Closed by ramschmaerchen** 2017-03-27 20:26 UTC
Labels: enhancement
